version: '3.4'

services:
 authenticationdb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: sql.authdb.container
    restart: always
    environment:
       ACCEPT_EULA: "Y"
       SA_PASSWORD: "dotvik@987"
    ports:
      - "1435:1433"

 catalogdb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: sql.catalogdb.container
    restart: always
    environment:
       ACCEPT_EULA: "Y"
       SA_PASSWORD: "dotvik@987"
    ports:
      - "1434:1433"

 basketdb:
    image: redis
    container_name: basket.redisdb.container
    restart: always
    ports:
      - "6379:6379"

 orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: sql.orderdb.container
    restart: always
    environment:
       ACCEPT_EULA: "Y"
       SA_PASSWORD: "dotvik@987"
    ports:
      - "1436:1433"
    volumes:
      - C:/MicroserviceAPP/data:/var/opt/mssql/data

 rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

 authentication.api:
    image: aspnetdocker/authapi:v1
    container_name: authentication.api.container
    restart: on-failure
    build:
      context: .
      dockerfile: Authentication.API/Dockerfile
    depends_on:
      - authenticationdb
    ports:
      - "8000:80"

 catalog.api:
    image: aspnetdocker/catalogapi:v1
    container_name: catalog.api.container
    restart: on-failure
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile
    depends_on:
      - catalogdb
    ports:
      - "8001:80"

 basket.api:
    image: aspnetdocker/basketapi:v1
    container_name: basket.api.container
    restart: on-failure
    build:
      context: .
      dockerfile: Basket.API/Dockerfile
    depends_on:
      - basketdb
      - rabbitmq
    ports:
      - "8002:80"

 ordering.api:
    image: aspnetdocker/orderapi:v1
    container_name: order.api.container
    restart: on-failure
    build:
      context: .
      dockerfile: Ordering.API/Dockerfile
    depends_on:
      - rabbitmq
      - orderdb
    ports:
      - "8003:80"