version: '3.4'

services:
 authentication.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:UserConnection=Server=authenticationdb;Initial Catalog=UserDb;Persist Security Info=False;User ID=SA;Password=dotvik@987"
    ports:
      - "80"

 catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:CatalogConnection=Server=catalogdb;Initial Catalog=CatalogDb;Persist Security Info=False;User ID=SA;Password=dotvik@987"
    ports:
      - "80"