version: '3.4'

services:
  catalog.api:
    image: aspnetdocker/catalogapi:v1
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  catalogdb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: always
    environment:
       ACCEPT_EULA: "Y"
       SA_PASSWORD: "dotvik@987"
    ports:
      - "1433:1433"
    volumes:
      - sqlbackup:/home/node/app

  basket.api:
    image: aspnetdocker/basketapi:v1
    build:
      context: .
      dockerfile: Basket.API/Dockerfile
    depends_on:
      - basketdb
    ports:
      - "8001:80"
  
  basketdb:
    image: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  sqlbackup:
